inherit_from: ./configs/Dynamic/YouTube/tokyo_walking1.yaml
scene: tokyo_walking1_droidw_mapping_full
max_frames: -1

mapping:
  enable: True
  online_plotting: False
  eval_before_final_ba: False

point_cloud:
  save_final: False
